# Generated by Django 4.0 on 2021-12-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('t', models.TextField(blank=True)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=10)),
                ('contact1', models.CharField(blank=True, max_length=10)),
                ('memories', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
