# Generated by Django 4.0 on 2022-01-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slamm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('blood', models.CharField(max_length=10)),
                ('t', models.TextField(blank=True)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=10)),
                ('contact1', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Slam',
        ),
    ]
