# Generated by Django 4.0 on 2022-01-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_slamm_delete_slam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slamm',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='slamm',
            name='contact',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
