# Generated by Django 4.0 on 2022-01-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_slamm_address_alter_slamm_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slamm',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='slamm',
            name='contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='slamm',
            name='contact1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='slamm',
            name='t',
            field=models.TextField(),
        ),
    ]
