# Generated by Django 4.0 on 2022-01-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_slamm_address_alter_slamm_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slamm',
            name='address',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='slamm',
            name='contact1',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='slamm',
            name='t',
            field=models.CharField(max_length=1000),
        ),
    ]
